version: '2'
services:
  proxy:
    build: ./proxy
    ports:
      - "8080:80"
    depends_on:
      - web
  web:
    build: ./web
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn yunyanjin.wsgi -b 0.0.0.0:8000"
    expose:
      - "8000"