version: '2'
services:
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    volumes:
      - ./web:/web
    depends_on:
      - web
  web:
    build: ./web
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata fixture.json && gunicorn yunyanjin.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./web:/web
    expose:
      - "8000"