# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170830_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='info',
        ),
        migrations.AddField(
            model_name='product',
            name='effect',
            field=models.TextField(blank=True, verbose_name='用途功效'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.TextField(blank=True, verbose_name='营养成分'),
        ),
    ]
